#!/bin/sh

set -e

case "$1" in
	configure)


	   # configuration files should not be modifiable by 
           # grafana user, as this can be a security issue

	# if $2 is set, this is an upgrade
	if ( [ -n $2 ] && [ "$RESTART_ON_UPGRADE" = "true" ] ) ; then
           # XXX Todo: Need to detect upgrade and decide what to do
	elif [ -z $2 ] ; then
	   # this is a fresh installation
	fi
	;;
esac
