#!/bin/sh

set -e

# Initial installation: $1 == 1
# Upgrade: $1 == 2, and configured to restart on upgrade
if [ $1 -eq 1 ] ; then
  # Nothing to do here - done via configure.sh instead
elif [ $1 -ge 2 ] ; then
  # XXX Todo - save off configs, restart 
  # XXX      - need a prerm scrip to remove warden conf file
fi
