name: Documentation CI
on:
  pull_request:
    paths: ["docs/sources/**"]
  workflow_dispatch:
jobs:
  vale:
    runs-on: ubuntu-latest
    container:
      image: grafana/vale:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Vale spellcheck
        run: >-
          vale --config ./.vale.ini --filter '.Name == "Grafana.Spelling"' docs/sources |
          /bin/reviewdog
          --conf /etc/vale/.reviewdog.yml
          --fail-on-error
          --reporter github-pr-review
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
